config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :topics, only: [:index, :create, :destroy]
      resources :values, only: [:index, :create]
    end
  end  
  root 'pages#index'
  get 'pages/index'
  
  resources :values
  resources :topics
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :values, dependent: :destroy
    
    validates :name, uniqueness: { message: "Topic name already exists" }
    before_validation :set_api_key
    
    attribute :number_of_values_to_keep, :integer, default: 30
    attribute :dashboard_number_of_values, :integer, default: 10
    attribute :show_on_dashboard, :boolean, default: true

    def set_api_key
        if not self.api_key.present?
            self.api_key = SecureRandom.base58(64)
        end
    end

end

app/controllers/api/v1/topics_controller.rb
class Api::V1::TopicsController < ApplicationController
  
  # bugfix
  # Necessary until this is fixed:
  # google: rails 6 json "Error occurred while parsing request parameters"
  # https://github.com/rails/rails/issues/34244
  def process_action(*args)
    super
    rescue ActionDispatch::Http::Parameters::ParseError => exception
      render status: 400, json: { errors: [ exception.message ] }
  end
  # end of bugfix

  rescue_from ActiveRecord::RecordInvalid, with: :render_unprocessable_entity_response
  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found_response

  before_action :set_topic, only: %i[ destroy ]
  
  def index
    topics = Topic.all.order(name: :asc)

    topics = topics.map do |topic| {
      name: topic.name,
      description: topic.description,
      show_on_dashboard: topic.show_on_dashboard,
      dashboard_name: topic.dashboard_name,
      dashboard_number_of_values: topic.dashboard_number_of_values
      }
    end

    render json: { topics: topics }.to_json, status: :ok
  end

  def create

    # @json = JSON.parse(request.body.read)
    @topic = Topic.new(topic_params)

    if @topic.save then
      render json: { name: @topic.name, created_at: @topic.created_at }, status: :ok
    else
      render json: { errors: @topic.errors }, status: :unprocessable_entity
    end
  end

  private

  	# Only allow a list of trusted parameters through.
    def topic_params
      params.permit(:api_key, :name, :description, :show_on_dashboard, :dashboard_name, :dashboard_number_of_values, :number_of_values_to_keep)
    end

    def set_topic
      api_key = request.headers[:HTTP_API_KEY] || params[:api_key]
      @topic = Topic.find_by!(api_key: api_key) rescue render_auth_error_response
    end  

    def render_invalid_sn_response
      render json: { error: 'Authorization error' }, status: :unprocessable_entity
    end

    def render_auth_error_response
      render json: { error: 'Authorization error' }, status: :unprocessable_entity
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1 or /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:name, :description, :api_key)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_with(model: topic) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :api_key %>
    <%= form.text_field :api_key %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Api key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= topic.description %></td>
        <td><%= topic.api_key %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @topic.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
</p>

<p>
  <strong>Api key:</strong>
  <%= @topic.api_key %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>