config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :topics, only: [:index, :create, :destroy]
      resources :values, only: [:index, :create]
    end
  end  
  root 'pages#index'
  get 'pages/index'
  
  resources :values
  resources :topics
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/value.rb
class Value < ApplicationRecord
    belongs_to :topic
end

app/controllers/api/v1/values_controller.rb
class Api::V1::ValuesController < ApplicationController
  
  # bugfix
  # Necessary until this is fixed:
  # google: rails 6 json "Error occurred while parsing request parameters"
  # https://github.com/rails/rails/issues/34244
  def process_action(*args)
    super
    rescue ActionDispatch::Http::Parameters::ParseError => exception
      render status: 400, json: { errors: [ exception.message ] }
  end
  # end of bugfix

  rescue_from ActiveRecord::RecordInvalid, with: :render_unprocessable_entity_response
  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found_response

  before_action :set_topic

  def create

    values = @json_params["values"]
    values.each do |v|
      @topic.values.create(value: v)
    end

    dashboard_values = @topic.values.order(created_at: :asc).last(@topic.dashboard_number_of_values)
    dashboard_data =  { "topic": @topic.name,
                        "labels": dashboard_values.map { |v| v.created_at },
                        "values": dashboard_values.map { |v| v.value }
                      }.to_json

    ActionCable.server.broadcast "dashboard_channel", dashboard_data
    
    render json: { results: values.count.to_s + ' value(s) successfully saved.'}, status: :ok
  end

  def index

    number = @json_params[:number] || 1
    values = @topic.values.order(created_at: :asc).last(number)
    values = values.map do |value|
      { value: value.value, created_at: value.created_at.to_formatted_s(:number) }
    end

    render json: { values: values }.to_json, status: :ok
  end

  def show
  end

  private

    def set_topic
      @json_params = JSON.parse(request.body.read)
      @topic = Topic.find_by!(name: @json_params["topic"]) rescue render_not_found_response
    end

    def value_params
      params.permit(:topic, :values[], :number)
    end

    def render_unprocessable_entity_response(exception)
      render json: exception.record.errors, status: :unprocessable_entity
    end

    def render_not_found_response()
      render json: { "error": "Topic not found in value_store" }.to_json, status: :not_found
    end

end

app/controllers/values_controller.rb
class ValuesController < ApplicationController
  before_action :set_value, only: %i[ show edit update destroy ]

  # GET /values or /values.json
  def index
    @values = Value.all
  end

  # GET /values/1 or /values/1.json
  def show
  end

  # GET /values/new
  def new
    @value = Value.new
  end

  # GET /values/1/edit
  def edit
  end

  # POST /values or /values.json
  def create
    @value = Value.new(value_params)

    respond_to do |format|
      if @value.save
        format.html { redirect_to value_url(@value), notice: "Value was successfully created." }
        format.json { render :show, status: :created, location: @value }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @value.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /values/1 or /values/1.json
  def update
    respond_to do |format|
      if @value.update(value_params)
        format.html { redirect_to value_url(@value), notice: "Value was successfully updated." }
        format.json { render :show, status: :ok, location: @value }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @value.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /values/1 or /values/1.json
  def destroy
    @value.destroy

    respond_to do |format|
      format.html { redirect_to values_url, notice: "Value was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_value
      @value = Value.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def value_params
      params.require(:value).permit(:topic_id, :value, :measured_at)
    end
end

app/helpers/values_helper.rb
module ValuesHelper
end

app/views/values/_form.html.erb
<%= form_with(model: value) do |form| %>
  <% if value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(value.errors.count, "error") %> prohibited this value from being saved:</h2>

      <ul>
        <% value.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :topic_id %>
    <%= form.number_field :topic_id %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :measured_at %>
    <%= form.date_select :measured_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/values/edit.html.erb
<h1>Editing Value</h1>

<%= render 'form', value: @value %>

<%= link_to 'Show', @value %> |
<%= link_to 'Back', values_path %>

app/views/values/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Values</h1>

<table>
  <thead>
    <tr>
      <th>Topic</th>
      <th>Value</th>
      <th>Measured at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @values.each do |value| %>
      <tr>
        <td><%= value.topic_id %></td>
        <td><%= value.value %></td>
        <td><%= value.measured_at %></td>
        <td><%= link_to 'Show', value %></td>
        <td><%= link_to 'Edit', edit_value_path(value) %></td>
        <td><%= link_to 'Destroy', value, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Value', new_value_path %>

app/views/values/new.html.erb
<h1>New Value</h1>

<%= render 'form', value: @value %>

<%= link_to 'Back', values_path %>

app/views/values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @value.topic_id %>
</p>

<p>
  <strong>Value:</strong>
  <%= @value.value %>
</p>

<p>
  <strong>Measured at:</strong>
  <%= @value.measured_at %>
</p>

<%= link_to 'Edit', edit_value_path(@value) %> |
<%= link_to 'Back', values_path %>